apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: ghcr.io/adrn1201/todo-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_URL
          value: mongodb://mongo:27017/todo-app
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: todo-app